server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  # 关闭缓存
  rabbitmq:
    host: 192.168.31.142
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务时间
