server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.31.142
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4G8atEH6tLcaTReh7JAe # 你自己的accessKeyId
    accessKeySecret: QS3i6RZV663rJpv9csIWFASE8HnUka # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_189520829 # 模板名称